flows:
  - "**"
executionOrder:
  continueOnFailure: false # default is true
  flowsOrder:
      - Test to Delete All Data
      - Test to add category
      - Test to add group
      - Test to add transaction